### ISSUE TITLE
Feature proposal: add previous and next buttons to navigate between lesson subsections 

### ISSUE THREAD

**Issue by andrew-1234** [ecoacoustics/website#34]
Background:
- Lessons are currently broken into three subsections/pages: requirements, presentation, and practical
- To navigate to the next or previous step in a lesson, a user has to find the appropriate heading in the side menu
- Buttons to navigate between subpages of a lesson could improve user experience

Proposal: 
- Using the existing `button` short code:
  - Add a `next step` and `previous step` button to the bottom of each lesson subsection page

**Comment by atruskie** [comment]
Questions:

- What is the navigation order?
- Does the button show on the presentation page as well?
- Why is it a button? And not a link (`<a href=""></a>`)?
- Would a shortcode even work?
- Have you considered any alternatives?
   - If so, why'd you reject them?
   - examples: scroll to top link, fixed position side menu
- Got a mock up for me?

**Comment by andrew-1234** [comment]
1. The navigation order I propose is:
   1. On Requirements page: Next button -> to Presentation
   2. On Presentation: Previous button (to Requirements) and Next button (to Practical)
   3. On Practical: Previous button (to Presentation)
   4. This way buttons will only act as a navigator between pages within a lesson rather than between lessons (which could impose an overall lesson "order")
2. Presentation page already has a type of next button on end slide. But for consistency I think it would make sense to include the buttons as well if they are on other pages. 
3. I believe the theme's button short code is calling an anchor element rather than a button element. And it is just styled to look like a button, which I think adds visual emphasis over a link, since the pages also contain many other hyperlinks. 
4. The advantages I can see for the short code is that it can accept either `relref` or `href` links. The short code also accepts additional classes, and we could create css subclasses for styling next and previous buttons, which makes the navigation buttons reusable across the website if needed. 
5. I considered a floating sidebar or floating navigation buttons, but I think these would be more intrusive options visually
6. This is an example of the button short code with a relref to next page. Ideally I was thinking to style next buttons on the right hand side of page, while previous buttons would be positioned on the left. 
![image](https://user-images.githubusercontent.com/22015718/203181867-e288b86f-3ea6-408f-bea3-09071d3af272.png)

Let me know your thoughts! Thanks!

**Comment by atruskie** [comment]
Ok I see you gave this a lot of thought. Nothing like an alternative viewpoint to clarify one's own. Here's where I settled:

1. Ordering: this is an unrelated concern. Ordering for lessons and sub-pages can be defined by the weight attribute that is provided by Hugo. Let's let hugo do its job and keep it simple.
    - I also think we can either link to the next previous lesson at the end of the list of sub-pages, OR link back to the list of lessons on every page. 
3. Does it show on the presentation page: Yes - it won't show on fullscreen though, so we don't really need to be worried about it - just like we aren't worried about the rest of the chrome (side menus, header, footer etc)
4. It should be an anchor absolutely. As for _should the anchor be styled as a button?_: My personal rule here is that any action that has a side effect is a button, any action that navigates is an anchor. This almost always lines up with semantic intent as well (so following that rule `<a>`s almost always look links, and `<button>`s almost always look like buttons). In this case we are talking about navigation, so let's keep link styling and add other visual hints (icons/padding) if needed to delimit the links.
5. Shortcodes: You can only use shortcodes in markdown. You'll need a partial to add this to a template - though as you point out, the `relref` and `ref` functions are good to use. Luckily both those functions are available in shortcodes and templates.
6. Positioning: agreed, just a row of links at the bottom
7. Here are some other designs I'd use as a reference:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/1452968/203193868-63d240a2-5887-4fe1-8808-ecaee7876b26.png">

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1452968/203194538-39a9676f-0e07-4dd7-bbbb-cdc3caaa5f30.png">

I'd suggest:

- one row, after all content, with a little more padding than usual
    -  left aligned link that shows previous page, or if none, previous lesson
    - right aligned link that shows next page, or if none, next lesson

---

If you're happy with those suggestions, feel free to start work and submit a PR.
